### ISSUE TITLE
Give priority to flexbox helpers

### ISSUE THREAD

**Issue by aqazix** [luxonauta/luxa#4]
Add "!important" to all flexbox helpers so that they can be applied properly.

**Comment by luxonauta** [comment]
Hi **aqazix**! Why do you need it? Are you building this :muscle: or do you want I to build it?

**Comment by aqazix** [comment]
Without this, helpers like .align-center and .justify-between won't work, as .lx-row's properties will overwrite it. Another solution is to create those helpers in .lx-row instead of separate classes.
I can do both.

**Comment by luxonauta** [comment]
Ah understood :monocle_face:, I think it will be better to just add the ``!important`` in the class property then!

**Comment by luxonauta** [comment]
**aqazix** in the most recent [commit](https://github.com/luxonauta/luxa/commit/7bb8d0a5914dc7b9ca0855d0f89a301153d84a39) from the [dev](https://github.com/luxonauta/luxa/tree/dev) branch, I fixed that. Thank you for your contribution!
